CREATE TABLE [dbo].[Pet] (
	[Pet_Id] INT IDENTITY (100000, 1) NOT NULL,
	[Pet_Name] NVARCHAR (50) NOT NULL,
	[Pet_Type] NVARCHAR (50) NOT NULL,
	[Pet_Colour] NVARCHAR (50) NOT NULL,
	PRIMARY KEY CLUSTERED ([Pet_Id] ASC)
);